### ISSUE TITLE
can't 

### ISSUE THREAD

**Issue by kokowski** [gillesdubois/LouxarenRyzenToshConfig#1]
Hello

**Comment by gillesdubois** [comment]
Hi,
I don't rly understand whats your problem, what do you mean by "you can't open the config.plist file". plist open just fine with Xcode, should be the same with proper tree.

Just a few informations : 
- SMBios is not set on the plist you need to inject them using a third party tool.
- I don't provide the AML files so you need to generate them by yourself
- Kext file need to be retrived and placed on the right directory
- For more infos, see official opencore guide

**Comment by gillesdubois** [comment]
Ping ?
